import 'package:flutter/material.dart';

// generated by https://m3.material.io/theme-builder

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFBDC2FF),
  onPrimary: Color(0xFF0013A0),
  primaryContainer: Color(0xFF1B2CC8),
  onPrimaryContainer: Color(0xFFDFE0FF),
  secondary: Color(0xFFFFB59F),
  onSecondary: Color(0xFF5E1600),
  secondaryContainer: Color(0xFF852300),
  onSecondaryContainer: Color(0xFFFFDBD0),
  tertiary: Color(0xFF8DCDFF),
  onTertiary: Color(0xFF00344F),
  tertiaryContainer: Color(0xFF004B70),
  onTertiaryContainer: Color(0xFFCAE6FF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1B1B1F),
  onBackground: Color(0xFFE4E1E6),
  surface: Color(0xFF1B1B1F),
  onSurface: Color(0xFFE4E1E6),
  surfaceVariant: Color(0xFF46464F),
  onSurfaceVariant: Color(0xFFC7C5D0),
  outline: Color(0xFF91909A),
  onInverseSurface: Color(0xFF1B1B1F),
  inverseSurface: Color(0xFFE4E1E6),
  inversePrimary: Color(0xFF3B4BDF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFBDC2FF),
  outlineVariant: Color(0xFF46464F),
  scrim: Color(0xFF000000),
);

// generated by AI
const instagramColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF405DE6), // Instagramの青
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF833AB4), // Instagramの紫
  onPrimaryContainer: Color(0xFFFFFFFF),
  secondary: Color(0xFFFDCB5C), // Instagramの黄色
  onSecondary: Color(0xFF000000),
  secondaryContainer: Color(0xFFFD1D1D), // Instagramの赤
  onSecondaryContainer: Color(0xFFFFFFFF),
  tertiary: Color(0xFFFCAF45), // オレンジ
  onTertiary: Color(0xFF000000),
  tertiaryContainer: Color(0xFFC13584), // 深いピンク
  onTertiaryContainer: Color(0xFFFFFFFF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1B1B1F),
  onBackground: Color(0xFFE4E1E6),
  surface: Color(0xFF1B1B1F),
  onSurface: Color(0xFFE4E1E6),
  surfaceVariant: Color(0xFF46464F),
  onSurfaceVariant: Color(0xFFC7C5D0),
  outline: Color(0xFF202020),
  onInverseSurface: Color(0xFF1B1B1F),
  inverseSurface: Color(0xFFE4E1E6),
  inversePrimary: Color(0xFF3B4BDF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF405DE6),
  outlineVariant: Color(0xFF46464F),
  scrim: Color(0xFF000000),
);
